package com.example.cp;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class MainActivity14 extends AppCompatActivity {
    TextView t1;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main14);
        t1 = (TextView) findViewById(R.id.tv5);
        t1.setText("\n\nOperators in Java\n" +
                "Operator in Java is a symbol that is used to perform operations. For example: +, -, *, / etc.\n" +
                "\n" +
                "There are many types of operators in Java which are given below:\n" +

                "Unary Operator,\n" +
                "Arithmetic Operator,\n" +
                "Shift Operator,\n" +
                "Relational Operator,\n" +
                "Bitwise Operator,\n" +
                "Logical Operator,\n" +
                "Ternary Operator and\n" +
                "Assignment Operator.\n"+"Java Keywords\n" +
                "Java keywords are also known as reserved words. Keywords are particular words that act as a key to a code. These are predefined words by Java so they cannot be used as a variable or object name or class name.\n" +
                "\n" +
                "List of Java Keywords\n" +
                "A list of Java keywords or reserved words are given below:\n" +
                "\n" +
                "abstract: Java abstract keyword is used to declare an abstract class. An abstract class can provide the implementation of the interface. It can have abstract and non-abstract methods.\n" +
                "boolean: Java boolean keyword is used to declare a variable as a boolean type. It can hold True and False values only.\n" +
                "break: Java break keyword is used to break the loop or switch statement. It breaks the current flow of the program at specified conditions.\n" +
                "byte: Java byte keyword is used to declare a variable that can hold 8-bit data values.\n" +
                "case: Java case keyword is used with the switch statements to mark blocks of text.\n" +
                "catch: Java catch keyword is used to catch the exceptions generated by try statements. It must be used after the try block only.\n" +
                "char: Java char keyword is used to declare a variable that can hold unsigned 16-bit Unicode characters\n" +
                "class: Java class keyword is used to declare a class.\n" +
                "continue: Java continue keyword is used to continue the loop. It continues the current flow of the program and skips the remaining code at the specified condition.\n" +
                "default: Java default keyword is used to specify the default block of code in a switch statement.");
    }
}